# Generated by Django 5.0.7 on 2024-08-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftrampa_id', models.IntegerField(db_index=True)),
                ('ruta', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annotation_id', models.CharField(blank=True, db_index=True, max_length=50)),
            ],
        ),
    ]
