# Generated by Django 5.0.7 on 2024-08-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow_annotator_ui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftrampa_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annotation_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('rect_x', models.FloatField()),
                ('rect_y', models.FloatField()),
                ('rect_width', models.FloatField()),
                ('rect_height', models.FloatField()),
                ('path', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftrampa_id', models.IntegerField(db_index=True)),
                ('ruta', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Annotations',
        ),
    ]
