# Generated by Django 5.0.7 on 2024-08-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow_annotator_ui', '0003_rename_image_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='rect_height',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='rect_width',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='rect_x',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='rect_y',
        ),
        migrations.AddField(
            model_name='annotation',
            name='p1_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='p1_y',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='p2_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='p2_y',
            field=models.IntegerField(null=True),
        ),
    ]
