# Generated by Django 5.0.7 on 2024-09-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow_annotator_ui', '0004_remove_annotation_rect_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
