# Generated by Django 5.0.7 on 2024-09-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow_annotator_ui', '0005_annotation_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='fecha_foto',
            field=models.DateTimeField(null=True),
        ),
    ]
