# Generated by Django 5.0.7 on 2024-09-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow_annotator_ui', '0006_annotation_fecha_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='fecha_foto',
        ),
        migrations.AddField(
            model_name='photo',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='fecha_foto',
            field=models.DateTimeField(null=True),
        ),
    ]
