# Generated by Django 5.0.7 on 2025-02-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow_annotator_ui', '0007_remove_annotation_checked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrizedSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
            ],
        ),
    ]
