# Generated by Django 5.0.7 on 2025-02-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow_annotator_ui', '0008_parametrizedspecies'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrizedspecies',
            name='clase',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='parametrizedspecies',
            name='familia',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='parametrizedspecies',
            name='genero',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='parametrizedspecies',
            name='orden',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='parametrizedspecies',
            name='phylum',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='parametrizedspecies',
            name='reino',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='parametrizedspecies',
            name='taxa_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
