# Generated by Django 5.0.7 on 2025-02-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow_annotator_ui', '0009_parametrizedspecies_clase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='indexed',
            field=models.BooleanField(default=False),
        ),
    ]
