# Generated by Django 5.0.7 on 2025-02-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow_annotator_ui', '0011_alter_photo_ftrampa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='ftrampa_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
